version: "3.8"
services:
  short-url-app:
    build:
      context: .
    container_name: short-url-app
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - redis


  redis:
    image: redis:latest
    ports:
      - "6379:6379"